version: '3.4'
services:
  lm_api_run:
    container_name: lm_api_run
    image: lm_api_run
    build:
      context: ./lm_service
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: run
      FLASK_RUN_PORT: 5000
    command: gunicorn -b 0.0.0.0:5000 -w 4 --timeout 120 'src:create_app()'
    ports:
      - "5000:5000"
  
  api_run:
    container_name: api_run
    image: api_run
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: run
      FLASK_RUN_PORT: 8090
    command: gunicorn -b 0.0.0.0:8090 -w 4 --timeout 120 'src:create_app()'
    ports:
      - "8090:8090"
  
  web_app:
    container_name: web_app
    image: web_app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    expose:
      - 8080
    ports:
      - "8080:80"