version: '3.4'
services:
  api_run:
    container_name: api_run
    image: api_run
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: run
      FLASK_RUN_PORT: 8090
    command: gunicorn -b 0.0.0.0:8090 -w 4 --timeout 120 'src:create_app()'
    ports:
      - "8090:8090"
