openapi: 3.0.1
info:
  title: Language Model Interface API
  description: A simple API to interact with a small language model
servers:
  - url: "/"
paths:
  "/predict":
    post:
      summary: Make a prediction with a selected model
      description: Run's the selected language model inference
      operationId: predict
      requestBody:
        description: Inputs for the model to generate a prediction
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model_name:
                  type: str
                  example: llama-1.1b-chat
                  description: Name of the model to be used
                prompt:
                  type: str
                  example: Tell me a joke!
                  description: Input for the text generation
                sys_msg:
                  type: str
                  example: Your job is to tell really funny jokes. Keep your answers short and concise.
                  description: Previous context for the language model
      responses:
        "200":
          description: All Ok, model will generate a prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string
                    description: Text generated by the model
        "400":
          description: Bad request, some parameter was invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid argument argument_name=argument_value
                    description: Incorrect argument
  "/models":
    get:
      summary: Gets all available models
      description: Gets all available models
      operationId: models
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                properties:
                  models:
                    type: array
                    description: Available models
