version: '3.4'
services:
  lm_api_run:
    container_name: lm_api_run
    image: lm_api_run
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: run
      FLASK_RUN_PORT: 5000
    command: gunicorn -b 0.0.0.0:5000 -w 4 --timeout 120 'src:create_app()'
    ports:
      - "5000:5000"